Release/20
snowplow/snowplow-docker pull request #148
Opened 2020-09-30 12:23 UTC by oguzhanunlu

2020-09-30 12:59 UTC, oguzhanunlu commented
[CI failure](https://travis-ci.org/github/snowplow/snowplow-docker/builds/731582392#L194-L207) is due to current Dockerfiles having issues per hadolint

2020-09-30 13:57 UTC, chuwy requested changes
`README` is still outdated.

@benjben you might also want to have a look.

2020-09-30 14:02 UTC, oguzhanunlu commented
oh, I forgot about README, thanks @chuwy , updating now

2020-09-30 14:46 UTC, benjben reviewed
Do we want to keep this repo now that all the components push their own Docker image with CI/CD ?

2020-09-30 14:48 UTC, oguzhanunlu commented
We maintain base images' Dockerfiles in this repository, @benjben

2020-10-16 17:01 UTC, oguzhanunlu commented
@chuwy @benjben I just wrapped my development on this PR. Could you have another look?

2020-10-21 15:17 UTC, chuwy approved these changes
Looks great. Awesome idea with Hadolint.

Two things should be changed though:

1. Still a lot of mentions of Bintray in README
2. I couldn't spot the difference between images, e.g. when should I use `base-debian` and when `base-alpine`

Otherwise - 👍

2020-10-21 15:17 UTC, chuwy commented on README.md
>  They are published in the [`snowplow-docker-registry.bintray.io`][registry] docker registry.
Wrong.

2020-10-22 07:08 UTC, benjben approved these changes
Awesome work @oguzhanunlu !!

Agreed with Anton that it would be good to know the difference between the 2 base images.

I would not put the versions in `docker pull` in the README, that's easily forgotten after an update.

2020-10-29 15:43 UTC, chuwy approved these changes

2020-10-29 15:54 UTC, merged